# This file is part of «Epigraphy of Medieval Rus'» database.
#
# Copyright (c) National Research University Higher School of Economics
#
# «Epigraphy of Medieval Rus'» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Epigraphy of Medieval Rus'» database is distributed
# in the hope  that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Epigraphy of Medieval Rus'» database,
# see <http://www.gnu.org/licenses/>.

easy_admin:
  site_name: Древнерусская эпиграфика
  translation_domain: admin
  user:
    name_property_path: fullName
  design:
    assets:
      css:
        - build/css/admin/common.css
      js:
        - build/js/admin/common.js
    menu:
      -
        label: menu.inscriptions
        icon: scroll
        entity: Inscription
      -
        label: menu.carriers
        icon: church
        entity: Carrier
      -
        label: menu.entities
        icon: font
        children:
          - CarrierCategory
          - CarrierType
          - Alphabet
          - ContentCategory
          - Material
          - PreservationState
          - WritingMethod
          - WritingType
      -
        label: menu.users
        icon: users
        entity: User
  list:
    title: page.list.title
    actions:
      -
        name: show
        icon: eye
        label: false
      -
        name: edit
        icon: pencil
        label: false
      -
        name: delete
        icon: trash
        label: false
  new:
    title: page.new.title
  edit:
    title: page.edit.title
  show:
    title: page.show.title
    actions: [-delete]
  entities:
    Inscription:
      class: App\Persistence\Entity\Epigraphy\Inscription\Inscription
      label: entity.inscription
      list:
        fields:
          - id
          - carrier
          -
            property: interpretations
            type: array
      form:
        fields:
          -
            type: 'section'
            label: form.inscription.section.commonData
          - conventionalDate
          - carrier
          -
            type: 'section'
            label: form.inscription.section.actualResearchInformation
          -
            property: zeroRow
            type: App\Form\ZeroRowType
          -
            type: 'section'
            label: form.inscription.section.interpretations
          -
            property: interpretations
            css_class: eomr-embedded-collection
            type: collection
            type_options:
              required: true
              entry_type: App\Form\InterpretationType
              by_reference: false
    Carrier:
      class: App\Persistence\Entity\Epigraphy\Carrier\Carrier
      label: entity.carrier
    CarrierCategory:
      class: App\Persistence\Entity\Epigraphy\Carrier\Category\CarrierCategory
      label: entity.carrierCategory
    CarrierType:
      class: App\Persistence\Entity\Epigraphy\Carrier\Type\CarrierType
      label: entity.carrierType
    Alphabet:
      class: App\Persistence\Entity\Epigraphy\Alphabet
      label: entity.alphabet
    ContentCategory:
      class: App\Persistence\Entity\Epigraphy\ContentCategory
      label: entity.contentCategory
    Material:
      class: App\Persistence\Entity\Epigraphy\Material
      label: entity.material
    PreservationState:
      class: App\Persistence\Entity\Epigraphy\PreservationState
      label: entity.preservationState
    WritingMethod:
      class: App\Persistence\Entity\Epigraphy\WritingMethod
      label: entity.writingMethod
    WritingType:
      class: App\Persistence\Entity\Epigraphy\WritingType
      label: entity.writingType
    User:
      class: App\Persistence\Entity\Security\User
      label: entity.user
      controller: App\Controller\Admin\UserController
      form:
        fields:
          - username
          - fullName
          -
            property: roles
            type: choice
            type_options:
              multiple: true
              expanded: true
              choices:
                - { form.user.roles.user: ROLE_USER}
                - { form.user.roles.editor: ROLE_EDITOR}
                - { form.user.roles.admin: ROLE_ADMIN}
                - { form.user.roles.superAdmin: ROLE_SUPER_ADMIN}
          -
            property: plainPassword
            type: password