# This file is part of «Epigraphy of Medieval Rus'» database.
#
# Copyright (c) National Research University Higher School of Economics
#
# «Epigraphy of Medieval Rus'» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Epigraphy of Medieval Rus'» database is distributed
# in the hope  that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Epigraphy of Medieval Rus'» database,
# see <http://www.gnu.org/licenses/>.

security:
  role_hierarchy:
    ROLE_ADMIN: [ ROLE_USER, ROLE_SONATA_ADMIN ]
    ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
  encoders:
    App\Persistence\Entity\Security\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Persistence\Entity\Security\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous:
        lazy: true
      guard:
        authenticators:
          - App\Security\AppLoginAuthenticator
      logout:
        path: app_logout
        target: app_login
  access_control:
    - { path: ^/admin/security.*, role: [ ROLE_SUPER_ADMIN ] }
    - { path: ^/admin.*, role: [ ROLE_ADMIN ] }
    - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
