# This file is part of «Epigraphy of Medieval Rus» database.
#
# Copyright (c) National Research University Higher School of Economics
#
# «Epigraphy of Medieval Rus» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Epigraphy of Medieval Rus» database is distributed
# in the hope  that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Epigraphy of Medieval Rus» database,
# see <http://www.gnu.org/licenses/>.

sonata_admin:
  title: Epigraphy of Medieval Rus
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
    groups:
      inscriptions:
        label_catalogue: admin
        label: menu.groups.inscriptions.label
        items:
          - admin.inscription
          - admin.alphabet
          - admin.content_category
          - admin.material
          - admin.preservation_state
          - admin.writing_type
          - admin.writing_method
        roles: [ ROLE_ADMIN ]
      carriers:
        label_catalogue: admin
        label: menu.groups.carriers.label
        items:
          - admin.carrier
          - admin.carrier_type
          - admin.carrier_category
        roles: [ ROLE_ADMIN ]
      media:
        label_catalogue: admin
        label: menu.groups.media.label
        items:
          - admin.file
        roles: [ ROLE_ADMIN ]
      security:
        label_catalogue: admin
        label: menu.groups.security.label
        items:
          - admin.user
        roles: [ ROLE_SUPER_ADMIN ]
  options:
    legacy_twig_text_extension: false
    use_icheck: false
  assets:
    extra_javascripts:
      - 'build/js/admin/inscription/edit.js'
    extra_stylesheets:
      - 'build/css/admin/inscription/edit.css'

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

services:
  admin.carrier:
    class: App\Admin\CarrierAdmin
    arguments: [ null, App\Persistence\Entity\Epigraphy\Carrier, null ]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.carrier_type:
    class: App\Admin\CarrierTypeAdmin
    arguments: [ null, App\Persistence\Entity\Epigraphy\CarrierType, null ]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.carrier_category:
    class: App\Admin\CarrierCategoryAdmin
    arguments: [ null, App\Persistence\Entity\Epigraphy\CarrierCategory, null ]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.alphabet:
    class: App\Admin\AlphabetAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\Alphabet, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.content_category:
    class: App\Admin\ContentCategoryAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\ContentCategory, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.material:
    class: App\Admin\MaterialAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\Material, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.preservation_state:
    class: App\Admin\PreservationStateAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\PreservationState, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.writing_type:
    class: App\Admin\WritingTypeAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\WritingType, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.writing_method:
    class: App\Admin\WritingMethodAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\WritingMethod, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.inscription:
    class: App\Admin\InscriptionAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\Inscription, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.interpretation:
    class: App\Admin\InterpretationAdmin
    arguments: [null, App\Persistence\Entity\Epigraphy\Interpretation, null]
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.file:
    class: App\Admin\FileAdmin
    arguments:
      - null
      - App\Persistence\Entity\Epigraphy\File
      - null
      - '@logger'
      - '@App\Persistence\Repository\Epigraphy\FileRepository'
      - '@App\DataStorage\DataStorageManagerInterface'
    tags:
      - { name: sonata.admin, manager_type: orm }
  admin.user:
    class: App\Admin\UserAdmin
    arguments:
      - null
      - App\Persistence\Entity\Security\User
      - null
      - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
      - '@Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface'
    tags:
      - { name: sonata.admin, manager_type: orm }