# This file is part of «Epigraphy of Medieval Rus'» database.
#
# Copyright (c) National Research University Higher School of Economics
#
# «Epigraphy of Medieval Rus'» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Epigraphy of Medieval Rus'» database is distributed
# in the hope  that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Epigraphy of Medieval Rus'» database,
# see <http://www.gnu.org/licenses/>.

parameters:
  locale: 'ru'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Persistence/Entity,Persistence/Migrations,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Menu\MenuBuilder:
    arguments: ['@knp_menu.factory', '@request_stack']
    tags:
      - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

  App\Portation\Registry\PortationRegistry:
    calls:
      - method: addExporter
        arguments:
          - xlsx
          - '@App\Portation\Exporter\XlsxExporter'
      - method: addImporter
        arguments:
          - xlsx
          - '@App\Portation\Importer\XlsxImporter'